[[cassandra.mapping-usage.events]]
= Lifecycle Events

The Cassandra mapping framework has several built-in `org.springframework.context.ApplicationEvent` events that your application can respond to by registering special beans in the `ApplicationContext`.
Being based on Spring's application context event infrastructure lets other products, such as Spring Integration, easily receive these events as they are a well known eventing mechanism in Spring-based applications.

To intercept an object before it goes into the database, you can register a subclass of javadoc:org.springframework.data.cassandra.core.mapping.event.AbstractCassandraEventListener[] that overrides the `onBeforeSave(…)` method.
When the event is dispatched, your listener is called and passed the domain object (which is a Java entity).
Entity lifecycle events can be costly and you may notice a change in the performance profile when loading large result sets.
You can disable lifecycle events on the javadoc:org.springframework.data.cassandra.core.CassandraTemplate#setEntityLifecycleEventsEnabled(boolean)[Template API].
The following example uses the `onBeforeSave` method:

====
[source,java]
----
include::example$mapping/BeforeSaveListener.java[tags=class]
----
====

Declaring these beans in your Spring `ApplicationContext` will cause them to be invoked whenever the event is dispatched.

The javadoc:org.springframework.data.cassandra.core.mapping.event.AbstractCassandraEventListener[] has the following callback methods:

* `onBeforeSave`: Called in `CassandraTemplate.insert(…)` and `.update(…)` operations before inserting or updating a row in the database but after creating the `Statement`.
* `onAfterSave`: Called in `CassandraTemplate…insert(…)` and `.update(…)` operations after inserting or updating a row in the database.
* `onBeforeDelete`: Called in `CassandraTemplate.delete(…)` operations before deleting row from the database.
* `onAfterDelete`: Called in `CassandraTemplate.delete(…)` operations after deleting row from the database.
* `onAfterLoad`: Called in the `CassandraTemplate.select(…)`, `.slice(…)`, and `.stream(…)` methods after each row is retrieved from the database.
* `onAfterConvert`: Called in the `CassandraTemplate.select(…)`, `.slice(…)`, and `.stream(…)` methods after converting a row retrieved from the database to a POJO.

NOTE: Lifecycle events are emitted only for root-level types.
Complex types used as properties within an aggregate root are not subject to event publication.

include::{commons}@data-commons::page$entity-callbacks.adoc[leveloffset=+1]

[[cassandra.entity-callbacks]]
=== Store-specific EntityCallbacks

Spring Data for Apache Cassandra uses the `EntityCallback` API for its auditing support and reacts on the following callbacks.

.Supported Entity Callbacks
[%header,cols="4"]
|===
| Callback
| Method
| Description
| Order

| `ReactiveBeforeConvertCallback`
`BeforeConvertCallback`
| `onBeforeConvert(T entity, CqlIdentifier tableName)`
| Invoked before a domain object is converted to `Statement`.
Domain objects can be updated to include the change in the `Statement`.
| `Ordered.LOWEST_PRECEDENCE`

| `ReactiveAuditingEntityCallback`
`AuditingEntityCallback`
| `onBeforeConvert(Object entity, CqlIdentifier tableName)`
| Marks an auditable entity _created_ or _modified_
| 100

| `ReactiveBeforeSaveCallback`
`BeforeSaveCallback`
| `onBeforeSave(T entity, CqlIdentifier tableName, Statement statement)`
| Invoked before a domain object is saved. +
Can modify the target object after the `Statement` has been created. The provided statement contains all mapped entity information but changes to the domain object are not included in the `Statement`.
| `Ordered.LOWEST_PRECEDENCE`

|===
