image:https://spring.io/badges/spring-data-cassandra/ga.svg[Spring Data for Apache Cassandra,link=https://projects.spring.io/spring-data-cassandra/#quick-start]
image:https://spring.io/badges/spring-data-cassandra/snapshot.svg[Spring Data for Apache Cassandra,link=https://projects.spring.io/spring-data-cassandra/#quick-start]

image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-cassandra%2Fmaster&subject=Moore%20(master)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-cassandra/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-cassandra%2F2.1.x&subject=Lovelace%20(2.1.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-cassandra/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-data-cassandra%2F1.5.x&subject=Ingalls%20(1.5.x)[link=https://jenkins.spring.io/view/SpringData/job/spring-data-cassandra/]

= Spring Data for Apache Cassandra

The primary goal of the https://projects.spring.io/spring-data[Spring Data] project is to make it easier to build Spring-powered applications that use new data access technologies such as non-relational databases, map-reduce frameworks, and cloud based data services.

The Spring Data for Apache Cassandra project aims to provide a familiar and consistent Spring-based programming model for new datastores while retaining store-specific features and capabilities. The Spring Data for Apache Cassandra project provides integration with the Apache Cassandra database. Key functional areas of Spring Data for Apache Cassandra are a CQL abstraction, a POJO centric model for interacting with an Apache Cassandra tables and easily writing a repository style data access layer.

== Getting Help

For a comprehensive treatment of all the Spring Data for Apache Cassandra features, please refer to:

* the https://docs.spring.io/spring-data/cassandra/docs/current/reference/html/[User Guide]
* the https://docs.spring.io/spring-data/cassandra/docs/current/api/[JavaDocs] have extensive comments in them as well.
* the home page of https://projects.spring.io/spring-data-cassandra[Spring Data for Apache Cassandra] contains links to articles and other resources.
* for more detailed questions, use https://stackoverflow.com/questions/tagged/spring-data-cassandra[Spring Data for Apache Cassandra on Stackoverflow].

If you are new to Spring as well as to Spring Data, look for information about https://projects.spring.io/[Spring projects].

== Quick Start

Prerequisites:
* Java 6
* https://docs.datastax.com/en/developer/driver-matrix/doc/javaDrivers.html[DataStax Java Driver for Apache Cassandra 3.x]
* Apache Cassandra 1.x, 2.x or 3.x

=== Maven configuration

Add the Maven dependency:

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-cql</artifactId>
  <version>${version}.RELEASE</version>
</dependency>

<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-cassandra</artifactId>
  <version>${version}.RELEASE</version>
</dependency>
----

If you would rather like the latest snapshots of the upcoming major version, use our Maven snapshot repository and declare the appropriate dependency version.

[source,xml]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-cql</artifactId>
  <version>${version}.BUILD-SNAPSHOT</version>
</dependency>

<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-cassandra</artifactId>
  <version>${version}.BUILD-SNAPSHOT</version>
</dependency>

<repository>
  <id>spring-libs-snapshot</id>
  <name>Spring Snapshot Repository</name>
  <url>http://repo.spring.io/libs-snapshot</url>
</repository>
----

=== CassandraTemplate

`CassandraTemplate` is the central support class for Cassandra database operations. It provides:

* Increased productivity by handling common Cassandra operations properly. Includes integrated object mapping between CQL Tables and POJOs.
* Exception translation into Spring's https://docs.spring.io/spring/docs/current/spring-framework-reference/html/dao.html#dao-exceptions[technology agnostic DAO exception hierarchy].
* Feature rich object mapping integrated with Spring’s Conversion Service.
* Annotation-based mapping metadata but extensible to support other metadata formats.

=== Spring Data repositories

To simplify the creation of data repositories Spring Data for Apache Cassandra provides a generic repository programming model. It will automatically create a repository proxy for you that adds implementations of finder methods you specify on an interface.

For example, given a `Person` class with first and last name properties, a `PersonRepository` interface that can query for `Person` by last name and when the first name matches a like expression is shown below:

[source,java]
----
public interface PersonRepository extends CrudRepository<Person, Long> {

  List<Person> findByLastname(String lastname);

  List<Person> findByFirstnameLike(String firstname);
}
----

The queries issued on execution will be derived from the method name. Extending `CrudRepository` causes CRUD methods being pulled into the interface so that you can easily save and find single entities and collections of them.

You can have Spring automatically create a proxy for the interface by using the following JavaConfig:

[source,java]
----
@Configuration
@EnableCassandraRepositories
class ApplicationConfig extends AbstractCassandraConfiguration {

  @Override
  public String getContactPoints() {
    return "localhost";
  }

  @Override
  protected String getKeyspaceName() {
    return "springdata";
  }
}
----

This sets up a connection to a local Apache Cassandra instance and enables the detection of Spring Data repositories (through `@EnableCassandraRepositories`). The same configuration would look like this in XML:

[source,xml]
----
<cassandra:cluster contact-points="localhost" port="9042" />

<cassandra:session keyspace-name="springdata" />

<cassandra:template id="cassandraTemplate" />

<cassandra:repositories base-package="com.acme.repository" />
----

This will find the repository interface and register a proxy object in the container. You can use it as shown below:

[source,java]
----
@Service
public class MyService {

  private final PersonRepository repository;

  @Autowired
  public MyService(PersonRepository repository) {
    this.repository = repository;
  }

  public void doWork() {

     repository.deleteAll();

     Person person = new Person();
     person.setFirstname("Oliver");
     person.setLastname("Gierke");
     person = repository.save(person);

     List<Person> lastNameResults = repository.findByLastname("Gierke");
     List<Person> firstNameResults = repository.findByFirstnameLike("Oli*");
 }
}
----

== What's included

Spring Data for Apache Cassandra consists of two modules:

* Spring CQL
* Spring Data for Apache Cassandra

You can choose among several approaches to form the basis for your Cassandra database access. Spring’s support for Apache Cassandra comes in different flavors. Once you start using one of these approaches, you can still mix and match to include a feature from a different approach.

=== Spring CQL

Spring CQL takes care of all the low-level details that can make Cassandra and CQL such a tedious API to develop with.

`CqlTemplate` is the classic Spring CQL approach and the most popular. This "lowest level" approach and all others use a `CqlTemplate` under the covers including schema generation support.

=== Spring Data Cassandra

Spring Data for Apache Cassandra adds object mapping, schema generation and repository support to the feature set.

`CassandraTemplate` wraps a `CqlTemplate` to provide result to object mapping and the use of `SELECT`, `INSERT`, `UPDATE` and `DELETE` methods instead of writing CQL statements. This approach provides better documentation and ease of use. Schema generation support supports fast bootstrapping by using mapped objects to create tables and user types.

== Contributing to Spring Data

Here are some ways for you to get involved in the community:

* Get involved with the Spring community on Stackoverflow and help out on the https://stackoverflow.com/questions/tagged/spring-data-cassandra[spring-data-cassandra] tag by responding to questions and joining the debate.
* Create https://jira.spring.io/browse/DATACASS[JIRA] tickets for bugs and new features and comment and vote on the ones that you are interested in.
* Github is for social coding: if you want to write code, we encourage contributions through pull requests from https://help.github.com/forking/[forks of this repository]. If you want to contribute code this way, please reference a JIRA ticket as well covering the specific issue you are addressing.
* Watch for upcoming articles on Spring by https://spring.io/blog[subscribing] to spring.io.

Before we accept a non-trivial patch or pull request we will need you to https://cla.pivotal.io/sign/spring[sign the Contributor License Agreement]. Signing the contributor’s agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions, and you will get an author credit if we do. If you forget to do so, you'll be reminded when you submit a pull request. Active contributors might be asked to join the core team, and given the ability to merge pull requests.

== Initial Contributors

Spring Data for Apache Cassandra was initially created and supported by the following
companies and individuals:

* David Webb
* Matthew Adams
* John McPeek
* http://www.prowaveconsulting.com[Prowave Consulting] - David Webb
* http://www.scispike.com[SciSpike] - Matthew Adams

== Running CI tasks locally

Since this pipeline is purely Docker-based, it's easy to:

* Debug what went wrong on your local machine.
* Test out a a tweak to your `test.sh` script before sending it out.
* Experiment against a new image before submitting your pull request.

All of these use cases are great reasons to essentially run what the CI server does on your local machine.

IMPORTANT: To do this you must have Docker installed on your machine.

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-cassandra-github adoptopenjdk/openjdk8:latest /bin/bash`
+
This will launch the Docker image and mount your source code at `spring-data-cassandra-github`.
+
2. `cd spring-data-cassandra-github`
+
Next, run your tests from inside the container:
+
3. `./mvnw clean dependency:list test -Dsort` (or whatever profile you need to test out)

Since the container is binding to your source, you can make edits from your IDE and continue to run build jobs.

If you need to test the `build.sh` script, do this:

1. `docker run -it --mount type=bind,source="$(pwd)",target=/spring-data-cassandra-github adoptopenjdk/openjdk8:latest /bin/bash`
+
This will launch the Docker image and mount your source code at `spring-data-cassandra-github`.
+
2. `cd spring-data-cassandra-github`
+
Next, try to package everything up from inside the container:
+
3. `./mvnw -Pci,snapshot -Dmaven.test.skip=true clean deploy`

IMPORTANT: This will attempt to deploy to artifactory, but without credentials, it will fail, leaving you simply with a built artifact.

NOTE: Docker containers can eat up disk space fast! From time to time, run `docker system prune` to clean out old images.
