[[cassandra.repositories]]
= Cassandra Repositories

[[cassandra-repo-intro]]
== Introduction

This chapter covers the details of the Spring Data Repository support for Apache Cassandra.
Cassandra's Repository support builds on the core Repository support explained in <<repositories>>.
So make sure you understand of the basic concepts explained there before proceeding.

[[cassandra-repo-usage]]
== Usage

To access domain entities stored in Apache Cassandra, you can leverage Spring Data's sophisticated Repository support
that eases implementing DAOs quite significantly. To do so, simply create an interface for your Repository:

.Sample Person entity
====
[source,java]
----
@Table
public class Person {

  @Id
  private String id;
  private String firstname;
  private String lastname;

  // … getters and setters omitted
}
----
====

We have a simple domain object here. Note that the entity has a property named `id` of type `String`.
The default serialization mechanism used in `CassandraTemplate` (which is backing the Repository support)
regards properties named id as row id.

.Basic Repository interface to persist Person entities
====
[source]
----
public interface PersonRepository extends CrudRepository<Person, String> {

  // additional custom finder methods go here
}
----
====

Right now this interface simply serves typing purposes, but we will add additional methods to it later.
In your Spring configuration simply add:

.General Cassandra repository Spring configuration
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:cassandra="http://www.springframework.org/schema/data/cassandra"
  xsi:schemaLocation="
    http://www.springframework.org/schema/data/cassandra
    http://www.springframework.org/schema/data/cassandra/spring-cassandra.xsd
    http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd">

    <cassandra:cluster port="9042"/>
    <cassandra:session keyspace-name="keyspaceName"/>

    <cassandra:mapping
            entity-base-packages="com.acme.*.entities">
    </cassandra:mapping>

    <cassandra:converter/>

    <cassandra:template/>

    <cassandra:repositories base-package="com.acme.*.entities"/>
</beans>
----
====

The `cassandra:repositories` namespace element will cause the base packages to be scanned for interfaces
extending `CrudRepository` and create Spring beans for each one found. By default, the Repositories will be
wired with a `CassandraTemplate` Spring bean called `cassandraTemplate`, so you only need to configure
`cassandra-template-ref` explicitly if you deviate from this convention.

If you'd rather like to go with JavaConfig use the `@EnableCassandraRepositories` annotation. The annotation carries
the same attributes as the namespace element. If no base package is configured the infrastructure will scan
the package of the annotated configuration class.

.JavaConfig for repositories
====
[source,java]
----
@Configuration
@EnableCassandraRepositories
class ApplicationConfig extends AbstractCassandraConfiguration {

  @Override
  protected String getKeyspaceName() {
    return "keyspace";
  }

  public String[] getEntityBasePackages() {
    return new String[] { "com.oreilly.springdata.cassandra" };
  }
}
----
====

As our domain Repository extends `CrudRepository` it provides you with basic CRUD operations.
Working with the Repository instance is just a matter of injecting the Repository as a dependency into a client.

.Basic access to Person entities
====
[source,java]
----
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
public class PersonRepositoryTests {

    @Autowired PersonRepository repository;

    @Test
    public void readsPersonTableCorrectly() {

      List<Person> persons = repository.findAll();
      assertThat(persons.isEmpty()).isFalse();
    }
}
----
====

Cassandra repositories support paging and sorting for paginated and sorted access to the entities. Cassandra paging requires a paging state to forward-only navigate through pages. A `Slice` keeps track of the current paging state and allows creation of a `Pageable` to request the next page.

.Paging access to Person entities
====
[source,java]
----
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
public class PersonRepositoryTests {

    @Autowired PersonRepository repository;

    @Test
    public void readsPagesCorrectly() {

      Slice<Person> firstBatch = repository.findAll(CassandraPageRequest.first(10));

      assertThat(firstBatch).hasSize(10);

      Page<Person> nextBatch = repository.findAll(firstBatch.nextPageable());

      // …
    }
}
----
====

NOTE: Cassandra repositories do not extend `PagingAndSortingRepository` because classic paging patterns using limit/offset are not applicable to Cassandra.

The sample creates an application context with Spring's unit test support, which will perform annotation-based
dependency injection into the test class. Inside the test cases (test methods) we simply use the Repository to query
the data store. We invoke the Repository query method that requests the all `Person` instances.

[[cassandra.repositories.queries]]
== Query methods

Most of the data access operations you usually trigger on a Repository result in a query being executed against
the Apache Cassandra database. Defining such a query is just a matter of declaring a method on the Repository interface.

.PersonRepository with query methods
====
[source,java]
----
public interface PersonRepository extends CrudRepository<Person, String> {

    List<Person> findByLastname(String lastname);                           <1>

    Slice<Person> findByFirstname(String firstname, Pageable pageRequest);  <2>

    List<Person> findByFirstname(String firstname, QueryOptions opts);      <3>

    List<Person> findByFirstname(String firstname, Sort sort);              <4>

    Person findByShippingAddress(Address address);                          <5>

    Person findFirstByShippingAddress(Address address);                     <6>

    Stream<Person> findAllBy();                                             <7>

    @AllowFiltering
    List<Person> findAllByAge(int age);                                     <8>
}
----
<1> The method shows a query for all people with the given `lastname`. The query will be derived from parsing
the method name for constraints which can be concatenated with `And`. Thus the method name will result in
a query expression of `SELECT * from person WHERE lastname = 'lastname'`.
<2> Applies pagination to a query. Just equip your method signature with a `Pageable` parameter and let the method return a `Slice` instance and we will automatically page the query accordingly.
<3> Passing a `QueryOptions` object will apply the query options to the resulting query before it's execution.
<4> Applies dynamic sorting to a query. Just add a `Sort` parameter to your method signature and Spring Data
will automatically apply ordering to the query accordingly.
<5> Shows that you can query based on properties which are not a primitive type using registered ``Converter``'s
in `CustomConversions`. Throws `IncorrectResultSizeDataAccessException` if more than one match found.
<6> Uses the `First` keyword to restrict the query to the very first result. Unlike 5, this method does
not throw an exception if more than one match was found.
<7> Uses a Java 8 `Stream` which reads and converts individual elements while iterating the stream.
<8> Shows a query method annotated with `@AllowFiltering` that allows server-side filtering.
====

NOTE: Querying non-primary key properties requires secondary indexes.

[cols="1,2,3", options="header"]
.Supported keywords for query methods
|===
| Keyword
| Sample
| Logical result

| `After`
| `findByBirthdateAfter(Date date)`
| `birthdate > date`

| `GreaterThan`
| `findByAgeGreaterThan(int age)`
| `age > age`

| `GreaterThanEqual`
| `findByAgeGreaterThanEqual(int age)`
| `age >= age`

| `Before`
| `findByBirthdateBefore(Date date)`
| `birthdate < date`

| `LessThan`
| `findByAgeLessThan(int age)`
| `age < age`

| `LessThanEqual`
| `findByAgeLessThanEqual(int age)`
| `age <= age`

| `In`
| `findByAgeIn(Collection ages)`
| `age IN (ages...)`

| `Like`, `StartingWith`, `EndingWith`
| `findByFirstnameLike(String name)`
| `firstname LIKE (name as like expression)`

| `Containing` on String
| `findByFirstnameContaining(String name)`
| `firstname LIKE (name as like expression)`

| `Containing` on Collection
| `findByAddressesContaining(Address address)`
| `addresses CONTAINING address`

| `(No keyword)`
| `findByFirstname(String name)`
| `firstname = name`

| `IsTrue`, `True`
| `findByActiveIsTrue()`
| `active = true`

| `IsFalse`,  `False`
| `findByActiveIsFalse()`
| `active = false`

|===

include::../{spring-data-commons-docs}/repository-projections.adoc[leveloffset=+2]

[[cassandra.repositories.queries.options]]
=== Query options

You can specify query options for query methods by passing a `QueryOptions` object
to apply options to the query before the actual query execution.
`QueryOptions` is treated as non-query parameter and isn't considered as query parameter value.

For static declaration of a consistency level, use the `@Consistency` annotation on query methods.
The declared consistency level is applied to the query each time it is executed.

Query options are applicable to derived and string `@Query` repository methods.

----
public interface PersonRepository extends CrudRepository<Person, String> {

    @Consistency(ConsistencyLevel.LOCAL_ONE)
    List<Person> findByLastname(String lastname);

    List<Person> findByFirstname(String firstname, QueryOptions options);
}
----

NOTE: You can control fetch size, consistency level and retry policy defaults by configuring these parameters
on the CQL API instances `CqlTemplate`, `AsyncCqlTemplate`, and `ReactiveCqlTemplate`. Defaults apply if the particular
query option is not set.

[[cassandra.repositories.misc]]
== Miscellaneous

[[cassandra.repositories.misc.cdi-integration]]
=== CDI Integration

Instances of the Repository interfaces are usually created by a container, and the Spring container is
the most natural choice when working with Spring Data. Spring Data for Apache Cassandra ships with
a custom CDI extension that allows using the repository abstraction in CDI environments. The extension
is part of the JAR so all you need to do to activate it is dropping the Spring Data for Apache Cassandra JAR
into your classpath. You can now set up the infrastructure by implementing a CDI Producer for the `CassandraTemplate`:

[source,java]
----
class CassandraTemplateProducer {

	@Produces
	@Singleton
	public Cluster createCluster() throws Exception {
		CassandraConnectionProperties properties = new CassandraConnectionProperties();

		Cluster cluster = Cluster.builder().addContactPoint(properties.getCassandraHost())
				.withPort(properties.getCassandraPort()).build();
		return cluster;
	}

	@Produces
	@Singleton
	public Session createSession(Cluster cluster) throws Exception {
		return cluster.connect();
	}

	@Produces
	@ApplicationScoped
	public CassandraOperations createCassandraOperations(Session session) throws Exception {

		MappingCassandraConverter cassandraConverter = new MappingCassandraConverter();
		cassandraConverter.setUserTypeResolver(new SimpleUserTypeResolver(session.getCluster(), session.getLoggedKeyspace()));

		CassandraAdminTemplate cassandraTemplate = new CassandraAdminTemplate(session, cassandraConverter);
		return cassandraTemplate;
	}

	public void close(@Disposes Session session) {
		session.close();
	}

	public void close(@Disposes Cluster cluster) {
		cluster.close();
	}
}
----

The Spring Data for Apache Cassandra CDI extension will pick up `CassandraOperations` available as CDI bean
and create a proxy for a Spring Data Repository whenever an bean of a Repository type is requested by the container.
Thus obtaining an instance of a Spring Data Repository is a matter of declaring an `@Inject`-ed property:

[source,java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----

