[[cassandra.repositories]]
= Cassandra repositories

[[cassandra-repo-intro]]
== Introduction

This chapter will point out the specialties for repository support for Cassandra. This builds on the core repository support explained in <<repositories>>. So make sure you've got a sound understanding of the basic concepts explained there.

[[cassandra-repo-usage]]
== Usage

To access domain entities stored in a Cassandra you can leverage our sophisticated repository support that eases implementing those quite significantly. To do so, simply create an interface for your repository:

TODO

[[cassandradb.repositories.queries]]
== Query methods

[[cassandradb.repositories.queries.delete]]
=== Repository delete queries

[[cassandradb.repositories.misc]]
== Miscellaneous

[[cassandradb.repositories.misc.cdi-integration]]
=== CDI Integration

The Spring Data Cassandra CDI extension will pick up the `CassandraTemplate` available as CDI bean and create a proxy for a Spring Data repository whenever an bean of a repository type is requested by the container. Thus obtaining an instance of a Spring Data repository is a matter of declaring an `@Inject`-ed property:

[source,java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {

    List<Person> people = repository.findAll();
  }
}
----
