[[cassandra.observability]]
== Observability

Getting insights from an application component about its operations, timing and relation to application code is crucial to understand latency.
Spring Data Cassandra ships with a Micrometer instrumentation through the Cassandra driver to collect observations during Cassandra interaction.
Once the integration is set up, Micrometer will create meters and spans (for distributed tracing) for each Cassandra statement.

To enable the instrumentation, apply the following configuration to your application:

====
[source,java]
----
@Configuration
class ObservabilityConfiguration {

  @Bean
  public ObservationBeanPostProcessor observationBeanPostProcessor(ObservationRegistry observationRegistry) {
    return new ObservationBeanPostProcessor(observationRegistry);                                           <1>
  }

  @Bean
  public SessionBuilderConfigurer getSessionBuilderConfigurer() {
    return sessionBuilder -> sessionBuilder.addRequestTracker(ObservationRequestTracker.INSTANCE);          <2>
  }

  class ObservationBeanPostProcessor implements BeanPostProcessor {

    public final ObservationRegistry observationRegistry;

    public ObservationBeanPostProcessor(ObservationRegistry observationRegistry) {
      this.observationRegistry = observationRegistry;
    }

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {

      if (bean instanceof CqlSession) {
        return ObservableCqlSessionFactory.wrap((CqlSession) bean, observationRegistry);
      }

      if (bean instanceof ReactiveSession) {
        return ObservableReactiveSessionFactory.wrap((ReactiveSession) bean, observationRegistry);
      }

      return BeanPostProcessor.super.postProcessAfterInitialization(bean, beanName);
    }
  }
}
----
<1> Wraps all CQL session objects (imperative/reactive Session API) to observe Cassandra statement execution.
<2> Integrate with the Cassandra driver to obtain success/error callbacks.
====

include::../../../../target/_conventions.adoc[]

include::../../../../target/_metrics.adoc[]

include::../../../../target/_spans.adoc[]

See also https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/#Cassandra[OpenTelemetry Semantic Conventions] for further reference.
