[[cassandra.reactive.repositories]]
= Reactive Cassandra Repositories


[[cassandra.reactive.repositories.intro]]
== Introduction

This chapter will outline the specialties handled by the reactive _Repository_ support for Apache Cassandra.
This builds on the core _Repository_ infrastructure explained in <<cassandra.repositories>>, so make sure
you have a good understanding of the basic concepts explained there.

Reactive usage is broken up into two phases: Composition and Execution.

Calling _Repository_ methods lets you compose a reactive sequence by obtaining ``Publisher``s and applying operators.
No I/O happens until now. Passing the reactive sequence to a reactive execution infrastructure,
such as {spring-framework-docs}web.html#web-reactive[Spring WebFlux]
or http://vertx.io/docs/vertx-reactive-streams/java/[Vert.x]), will subscribe to the publisher and initiate
the actual execution.


[[cassandra.reactive.repositories.libraries]]
== Reactive Composition Libraries

The reactive space offers various reactive composition libraries. The most common libraries are
https://github.com/ReactiveX/RxJava[RxJava] and https://projectreactor.io/[Project Reactor].

Spring Data for Apache Cassandra is built on top of the https://github.com/datastax/java-driver[DataStax Cassandra Driver].
The driver is not reactive but the asynchronous capabilities allow us to adopt and expose the `Publisher` APIs
in order to provide maximum interoperability by relying on the http://www.reactive-streams.org/[Reactive Streams] initiative.
Static APIs, such as `ReactiveCassandraOperations`, are provided by using Project Reactor's `Flux` and `Mono` types.
Project Reactor offers various adapters to convert reactive wrapper types (`Flux` to `Observable` and vice versa)
but conversion can easily clutter your code.

Spring Data's _Repository_ abstraction is a dynamic API, mostly defined by you and your requirements,
as you are declaring query methods. Reactive Cassandra _Repositories_ can be either implemented using RxJava
or Project Reactor wrapper types by simply extending from one of the library-specific repository interfaces:

* `ReactiveCrudRepository`
* `ReactiveSortingRepository`
* `RxJava2CrudRepository`
* `RxJava2SortingRepository`

Spring Data converts reactive wrapper types behind the scenes so that you can stick to your favorite composition library.


[[cassandra.reactive.repositories.usage]]
== Usage

To access entities stored in Apache Cassandra, you can leverage Spring Data's sophisticated _Repository_ support,
which eases implementing DAOs quite significantly. To do so, simply create an interface for your _Repository_:

.Sample Person entity
====
[source,java]
----
@Table
public class Person {

  @Id
  private String id;
  private String firstname;
  private String lastname;

  // … getters and setters omitted
}
----
====

We have a simple domain object here. Note that the entity has a property named "`id`" of type `String`.
The default serialization mechanism used in `CassandraTemplate` (which is backing the _Repository_ support)
regards properties named "id" as the row id.

.Basic repository interface to persist Person entities
====
[source]
----
public interface ReactivePersonRepository extends ReactiveSortingRepository<Person, Long> {

  Flux<Person> findByFirstname(String firstname);                                <1>

  Flux<Person> findByFirstname(Publisher<String> firstname);                     <2>

  Mono<Person> findByFirstnameAndLastname(String firstname, String lastname);    <3>

  Mono<Person> findFirstByFirstname(String firstname);                           <4>

  @AllowFiltering
  Flux<Person> findByAge(int age);                                               <5>
}
----
<1> The method shows a query for all people with the given firstname. The query will be derived parsing the method name for constraints which can be concatenated with And and Or. Thus the method name will result in a query expression of `SELECT * FROM person WHERE firstname = :firstname`.
<2> The method shows a query for all people with the given firstname once the firstname is emitted via the given `Publisher`.
<3> Find a single entity for given criteria. Completes with `IncorrectResultSizeDataAccessException` on non unique results.
<4> Unlike 3, the first entity is always emitted even if the query yields more result rows.
<5> Shows a query method annotated with `@AllowFiltering` that allows server-side filtering.
====

For JavaConfig, use the `@EnableReactiveCassandraRepositories` annotation. The annotation carries the very same attributes
like the corresponding XML namespace element. If no base package is configured the infrastructure will scan the package
of the annotated configuration class.

.JavaConfig for repositories
====
[source,java]
----
@Configuration
@EnableReactiveCassandraRepositories
class ApplicationConfig extends AbstractReactiveCassandraConfiguration {

  @Override
  protected String getKeyspaceName() {
    return "keyspace";
  }

  public String[] getEntityBasePackages() {
    return new String[] { "com.oreilly.springdata.cassandra" };
  }
}
----
====

Since our domain _Repository_ extends `ReactiveSortingRepository`, it provides you with CRUD operations
as well as methods for sorted access to the entities. Working with the _Repository_ instance is just a matter of
dependency injecting it into a client.

.Sorted access to Person entities
====
[source,java]
----
public class PersonRepositoryTests {

    @Autowired ReactivePersonRepository repository;

    @Test
    public void sortsElementsCorrectly() {
        Flux<Person> people = repository.findAll(Sort.by(new Order(ASC, "lastname")));
    }
}
----
====

[[cassandra.reactive.repositories.features]]
== Features

Spring Data's Reactive Cassandra support comes with the same set of features as
<<cassandra.repositories,imperative repositories>>.

The following features are supported:

* Query Methods using <<cassandra.repositories.queries,String queries and Query Derivation>>
* <<projections>>

NOTE: Query methods must return a reactive type. Resolved types (`User` vs. `Mono<User>`) are not supported.
