This document is the reference guide for Spring Data support for Cassandra. It explains Cassandra module concepts,
semantics and the syntax for various stores namespaces.

This section provides a basic introduction to Spring, Spring Data and the Cassandra database. The rest of the document
refers only to Spring Data for Apache Cassandra features and assumes the user is familiar with Cassandra as well as
core Spring concepts.

[float]
[[get-started:first-steps:spring]]
=== Knowing Spring

Spring Data uses the Spring Framework's http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/[core]
functionality, such as the http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans[IoC] container,
http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#validation[validation, type conversion and data binding],
http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#expressions[expression language],
http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#aop[AOP],
http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#jmx[JMX integration],
http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#dao[DAO support], and specifically
the http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#dao-exceptions[DAO Exception Hierarchy].

While it is not important to know the Spring APIs, understanding the concepts behind them is. At a minimum, the idea
behind IoC should be familiar no matter what IoC container you choose to use.

The core functionality of the Cassandra support can be used directly, with no need to invoke the IoC services
of the Spring container. This is much like `JdbcTemplate`, which can be used 'standalone' without any other services
of the Spring container. To leverage all the features of Spring Data Cassandra, such as the repository support,
you will need to configure some parts of the library using Spring.

To learn more about Spring, you can refer to the comprehensive (and sometimes disarming) http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/[documentation]
that explains in detail the Spring Framework. There are a lot of articles, blog entries and books on the matter.
Take a look at the Spring Framework http://projects.spring.io/spring-framework/[home page] for more information.

[float]
[[get-started:first-steps:nosql]]
=== Knowing NoSQL and Cassandra

NoSQL stores have taken the storage world by storm. It is a vast domain with a plethora of solutions, terms and patterns
(to make things worse, even the term itself has multiple http://www.google.com/search?q=nosoql+acronym[meanings]).
While some of the principles are common, it is crucial that the user is familiar to some degree with
the Cassandra Columnar NoSQL Datastore supported by Spring Data Cassandra. The best way to get acquainted with Cassandra
is to read the documentation and follow the examples.  It usually doesn't take more then 5-10 minutes to go through them
and if you are coming from a RDBMS background, many times these exercises can be an eye opener.

The starting ground for learning about Cassandra is http://cassandra.apache.org/[cassandra.apache.org/]. Also, here is
a list of other useful resources:

* http://planetcassandra.org/[Planet Cassandra] site has many valuable resources for Cassandra best practices.
* The http://datastax.com/[DataStax] site offers http://www.datastax.com/what-we-offer/products-services/support[commercial support]
and many resources, including, but not limited to, http://docs.datastax.com/en/landing_page/doc/landing_page/current.html[documentation],
http://docs.datastax.com/en/landing_page/doc/landing_page/current.html[DataStax Academy], a http://www.datastax.com/dev/blog[Tech Blog]
and so on.
